##version: '3.9'

services:
  web:
    build: .
    container_name: m-web
    ports:
      - "80:80"
    volumes:
      - /home/marcaos/Coding/www/php_docker_Proj2:/var/www/html
    links:
      - db    
  db:
    image: mysql:latest
    container_name: m-mysql
    ports:
      - "3306:3306"
    volumes:
      - /home/marcaos/Coding/.lib/mysql:/var/lib/mysql
    environment: # Estudar variáveis de ambiente '.env'
      #MYSQL_USER: ${MYSQL_USER}
      #MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    

